import { CapturedAsset, ResolvedAsset, FetchedAsset, ProbedAsset, EncodedAsset, BuiltAsset } from "../asset";
import { Encoder, EncodeSpec } from "../encoder";
import { Cache } from "../cache";

/** Configures server behaviour. */
export type Options = {
    /** Local directory under which project's static files are stored. Required to resolve
     *  file paths of relative content sources; <code>./public</code> by default. */
    root: string;
    /** Regular expressions to use for capturing transformed assets syntax.
     *  Expects <code><url></code>, <code><alt></code> and <code><spec></code> capture groups
     *  (alt and spec are optional). By default, captures Markdown image syntax with spec defined as
     *  query params after alt: <code>!\[(?<alt>.*?)(?<spec>\?\S+?)?]\((?<url>\S+?)\)</code> */
    regex: RegExp[];
    /** Custom asset resolvers executed in order before the built-in resolver. Use to override the way
     *  asset info is resolved from captured syntax or add support for custom asset types and/or syntax. */
    resolvers: AssetResolver[];
    /** Custom asset HTML builders executed in order before the built-in builder. Use to override HTML
     *  generated by the server or add support for custom asset types. */
    builders: AssetBuilder[];
    /** Custom asset servers executed in order before the built-in server. Use to prepare generated files
     *  to be served (eg, copy to the static assets dir or upload to a CDN) and resolve the served URL. */
    servers: AssetServer[];
    /** Image source to show while content is loading. When cover generation is enabled in encode options,
     *  will use specified source as a fallback for legacy browsers, otherwise will use the
     *  source for all covers. Empty base64-encoded image is used by default for compatibility;
     *  assign <code>null</code> to disable covers completely. */
    cover: string | null;
    /** Default width threshold for the transformed assets, in pixels. When source asset is larger,
     *  will downscale it while preserving the original aspect. In case the source is 2x or larger,
     *  will as well generate additional "dense" variant that will be shown on high-dpi displays.
     *  This option is ignored when asset has width explicitly assigned via spec syntax. */
    width: number | null;
    /** Configure logging behaviour; assign <code>null</code> to disable logging. */
    log: LogOptions | null;
    /** Configure caching behaviour; assign <code>null</code> to disable caching. */
    cache: CacheOptions | null;
    /** Configure remote content fetching. */
    fetch: FetchOptions;
    /** Configure content encoding. */
    encode: EncodeOptions;
    /** Configure document transformation process. */
    transform: TransformOptions;
};

/** User-defined asset resolver. Given captured asset syntax, resolves asset type,
 *  content locations and specs (in-place). Return false when the resolver can't or shouldn't
 *  handle the asset, in which case it'll be handled by next resolvers in the chain. */
export type AssetResolver = (asset: ResolvedAsset) => boolean | Promise<boolean>;

/** User-defined asset HTML builder. Given encoded asset(s), build HTML (in-place for all the input
 *  assets) to replace captured syntax in the transformed document. May include additional merged
 *  assets when associated syntax were joined via "merge" spec. Return false when the builder can't
 *  or shouldn't  handle the assets, in which case they'll be handled by next builders in the chain. */
export type AssetBuilder = (asset: BuiltAsset, merges?: BuiltAsset[]) => boolean | Promise<boolean>;

/** User-defined asset server. Given full path to a content file and associated asset info,
 *  return URL under which the file will be served and prepare the file to be served (eg, copy to
 *  the static assets dir or upload to a CDN). Return null when the server can't or shouldn't
 *  handle the asset, in which case it'll be handled by next servers in the chain. */
export type AssetServer = (path: string, asset: Readonly<EncodedAsset>) => null | Promise<string | null>;

/** Configures logging behaviour. */
export type LogOptions = {
    /** Logs informational message, such as which assets were downloaded and encoded;
     *  assign <code>null</code> to disable logging informational messages. */
    info: ((msg: string) => void) | null;
    /** Logs warning message, such as a non-fatal issue with encoding process;
     *  assign <code>null</code> to disable logging warning messages. */
    warn: ((msg: string) => void) | null;
    /** Logs error message associated with a failed procedure;
     *  assign <code>null</code> to disable logging error messages. */
    err: ((msg: string) => void) | null;
};

/** Configures server cache. */
export type CacheOptions = {
    /** Local directory where the build cache files are stored. When building static apps (SPA) on CI,
     *  consider checking-in the cache directory to boost remote build processes;
     *  <code>./node_modules/.cache/imgit</code> by default. */
    root: string;
    /** Persists specified cache instance for consequent runs; writes to file system by default.
     *  When running SSR under constraint environments (eg, on edge), override to use alternative APIs. */
    save: (cache: Readonly<Cache>) => Promise<void>;
    /** Loads cache instance of a previous run; reads from file system by default.
     *  When running SSR under constraint environments (eg, on edge), override to use alternative APIs. */
    load: () => Promise<Cache>;
}

/** Configures remote assets downloading behaviour. */
export type FetchOptions = {
    /** Local directory to store downloaded remote content files;
     *  <code>./node_modules/.cache/imgit/fetched</code> by default. */
    root: string;
    /** How long to wait when downloading remote asset, in seconds; 30 by default. */
    timeout: number;
    /** How many times to restart the download when request fails; 3 by default. */
    retries: number;
    /** How long to wait before restarting a failed download, in seconds; 6 by default.*/
    delay: number;
};

/** Configures assets encoding. */
export type EncodeOptions = {
    /** Local directory to store encoded content and generated files, such as covers;
     *  <code>./node_modules/.cache/imgit/encoded</code> by default. */
    root: string;
    /** Implementation to probe and encode media files with; specify to swap ffmpeg used by default. */
    encoder: Encoder;
    /** Encode parameters mapped by content MIME type; matched in order. */
    specs: [string | Readonly<RegExp>, Readonly<EncodeSpec>][];
    /** Configure cover generation; specify <code>null</code> to disable per-asset cover generation. */
    cover: EncodeSpec & {
        /** Tag to append to the names of generated cover files; <code>-cover</code> by default. */
        suffix: string;
    } | null;
    /** Configure safe files generation, that is fallbacks used in case source content is not considered
     *  compatible with legacy or any browsers, such as AVIF or PSD; specify <code>null</code> to disable. */
    safe: {
        /** MIME content types considered safe or compatible with most browsers. When source asset content is
         *  not of the specified type, will create a fallback content with a compatible type; otherwise will
         *  use source content for fallback. */
        types: (string | Readonly<RegExp>)[]
        /** Tag to append to the names of generated safe files; <code>-safe</code> by default. */
        suffix: string;
    } | null;
    /** Configure dense files generation, that is variants with 2x the resolution of the main content
     *  shown on high-dpi displays. Dense variants are generated when either global or per-asset spec
     *  "width" option is specified with value less than the source content width by 2x or more;
     *  assign <code>null</code> to disable dense file generation. */
    dense: {
        /** Tag to append to the names of generated dense files; <code>-dense</code> by default. */
        suffix: string;
    } | null;
    /** Tag to append to the names of all the encoded/generated files; <code>-imgit</code> by default. */
    suffix: string;
};

/** Configures document transformation process. */
export type TransformOptions = {
    /** 1st phase: finds assets to transform in the document with specified content. */
    capture: (content: string) => CapturedAsset[] | Promise<CapturedAsset[]>;
    /** 2nd phase: resolves type, content locations and specs of the captured syntax. */
    resolve: (assets: CapturedAsset[]) => ResolvedAsset[] | Promise<ResolvedAsset[]>;
    /** 3rd phase: downloads file content for the resolved assets. */
    fetch: (assets: ResolvedAsset[]) => FetchedAsset[] | Promise<FetchedAsset[]>;
    /** 4th phase: probes downloaded asset files to identify their content properties. */
    probe: (assets: FetchedAsset[]) => ProbedAsset[] | Promise<ProbedAsset[]>;
    /** 5th phase: generates optimized versions of the source content files. */
    encode: (assets: ProbedAsset[]) => EncodedAsset[] | Promise<EncodedAsset[]>;
    /** 6th phase: builds HTML for the optimized asset content. */
    build: (assets: EncodedAsset[]) => BuiltAsset[] | Promise<BuiltAsset[]>;
    /** 7th phase: replaces captured syntax with the built HTML; returns modified document content. */
    rewrite: (content: string, assets: BuiltAsset[]) => string | Promise<string>;
};
